config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"


  devise_for :users
  resources :users, only: [:index, :show] do
    resources :abouts, only: [:create, :new, :edit, :update]
  end

  resources :posts do
    resources :comments
    resource :likes, only: [:create, :destroy]
  end

  resources :chatrooms, only: [:show, :index, :create] do
    resources :messages, only: [:create]
  end

  resources :chat_room_users, only: [:create]

  resources :locations, only: [:create, :update]
end

app/models/about.rb
class About < ApplicationRecord
  belongs_to :user
end

app/models/add_category_to_post.rb
class AddCategoryToPost < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :chat_room_users, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user
  has_one_attached :photo
  has_many :likes, dependent: :destroy

  has_many :comments, dependent: :destroy


  private

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :avatar
  has_one :location
  has_many :chatrooms
  has_many :messages
  has_many :chat_room_users
  has_one :about, dependent: :destroy

  private

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  def already_have_address?
    self.location.presence == nil
  end

end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def new
    @about = About.new
  end

  def create
    @about = About.new(about_params)
    @about.user_id = current_user.id

    if @about.save
      redirect_to root_path, notice: "Successfully set profile information"
    else
      redirect_to root_path, notice: "Failed to save profile information"
    end
  end

  def edit
    @about = About.find(params[:id])
  end

  def update
    @about = About.find(params[:id])
    if @about.update(about_params)
      redirect_to root_path, notice: "Successfully updated profile information"
    else
      redirect_to root_path, notice: "Failed to update profile information"
    end
  end

  private

  def about_params
    params.require(:about).permit(:profile, :number_of_countries, :number_of_met_people, :number_of_friends)
  end

end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController

  def create
    user = User.find(params[:format])
    if user.chat_room_users.present?
      active_chats = User.find(params[:format]).chat_room_users
      chat_exist = false
      chat_room_id = 0

      active_chats.each do |active_chat|
        if current_user.chat_room_users.find_by(chatroom_id:active_chat.chatroom_id)
          chat_exist = true
          chat_room_id = active_chat.chatroom_id
        end
      end
    end

    if !chat_exist
      @chatroom = Chatroom.create
      ChatRoomUser.create(chatroom_id: @chatroom.id, user_id:user.id)
      ChatRoomUser.create(chatroom_id: @chatroom.id, user_id:current_user.id)
      
      redirect_to chatroom_path(@chatroom.id)
    else
      redirect_to chatroom_path(chat_room_id)
    end

  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end

  def index
    if current_user.chat_room_users.presence
      @chating_list = current_user.chat_room_users
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index

  end

  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_param)
    @comment.post_id = @post.id
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to request.referer, notice: "Success!"
    else
      redirect_to request.referer, notice: "Failed to leave a comment..."
    end
  end


  private

  def comment_param
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new(user_id:current_user.id, post_id: params[:post_id])
    @like.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: "message", locals: {message: @message})
      )
      head :ok
    else
      render "chatrooms/show", status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path
    else
      redirect_to new_post_path
    end
  end

  def show
    @post = Post.find(params[:id])
    @markers = [
      {
        lat: @post.latitude,
        lng: @post.longitude,
        info_window: render_to_string(partial: "popup", locals: {post: @post})
      }]

      if current_user.location.present?
        @current = [{address: current_user.location}]
      end
  end

  def index
    @comment = Comment.new
    @posts = Post.all
    @markers = @posts.geocoded.map do |post|
      {
        lat: post.latitude,
        lng: post.longitude,
        info_window: render_to_string(partial: "popup", locals: {post: post})
      }
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post), notice: 'Successfully updated !'
    else
      redirect_to edit_post(@post), alert: 'Oops! Failed to update!'
    end

  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to root_path, notice: "Successfully deleted"
    else
      redirect_to post_path, alert: "Failed to delete"
    end
  end

  private

  def post_params
    params.require(:post).permit(:content, :address, :category, :title, :photo)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Triptip</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    

  </head>

  <body>
  <%= render "shared/navbar" %>
  <%= render "shared/flashes" %>
    <%= yield %>
  <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %>
  <%= render "shared/logged_in_home" %>
<% else %>
  <%= render "shared/landing_home" %>
<% end %>

app/views/shared/_card_home.html.erb
<h3>Suggestions in your destination</h3>
<div class="mt-4 col-lg-3 d-flex row flex-row flex-nowrap overflow-auto" style="margin: 0 auto; width: 1100px">
  <% @posts.each do |post| %>
    <div class="card me-5 corner shadow" style="width: 250px;">
      <% if post.photo.attached? %>
          <%= cl_image_tag post.photo.key, height: 200, width: 250, crop: :fill %>
        <% else %>
          <img style="width:100%;" src="https://elcomercio.pe/resizer/VBT_5K1XgES0ec_-SjauADEHd_I=/1200x800/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/YZE2DDHNKNDXJNSFLFTAKPUUGU.jpg" alt="">
        <% end %>
        <div class="d-flex">
          <img class="circle" src="https://www.freeiconspng.com/thumbs/account-icon/account-icon-33.png" style="height:30px; width:30px" alt="">
          <%= User.find(post.user_id).first_name %>
          <h5 class="ms-2 card-title">Card title</h5>
        </div>
      <div class="card-body">

        <p class="card-text" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap;"><%= post.content %></p>
        <%= link_to "Show", post_path(post), class:"btn btn-light" %>
        <i class="fa-regular fa-comment"></i>
        <i class="fa-solid fa-heart"></i>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_current_address_input.html.erb
<% if current_user.location.presence == nil %>
  <%= simple_form_for Location.new, data: {turbo: false} do |f|%>
  <%= f.input :address, input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"}, wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
    <div class="form-actions">
      <%= f.button :submit, "Set address", class:"btn btn-dark" %>
    </div>
  <% end %>
<% else %>
  <div class="d-flex justify-content-center">
    <h4><i class="fa-solid fa-location-dot"></i></h4>
    <%= current_user.location.address %>
  </div>
    <%= simple_form_for (current_user.location), data: {turbo: false} do |f|%>
      <div class="d-flex justify-content-center">
        <%= f.input :address, label: false, input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
        <%= f.button :submit, "Change", class:"btn btn-dark", style:"margin-bottom:20px;" %>
      </div>
    <% end %>
<% end %>

app/views/shared/_faker.html.erb
<div class="container chatroom"
  data-controller="chatroom-subscription"
  data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>">

  <div class="messages" data-chatroom-subscription-target="messages">
    <% @chatroom.messages.each do |message| %>
      <div id="message-<%= message.id %>">
        <small>
          <strong><%= message.user.first_name%></strong>
          <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
        </small>
        <p><%= message.content %></p>
      </div>
    <% end %>
  </div>

  <%= simple_form_for [@chatroom, @message],
  html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" },
  class: "d-flex" } do |f|
  %>

  <%= f.input :content,
    label: false,
    placeholder: "New message",
    wrapper_html: {class: "flex-grow-1"}
  %>
  <%= f.submit "Send", class: "btn btn-primary mb-3" %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer" style="margin-top:100px; height: 500px; background-color: #3d4045; color:white">
<div class="container " style="padding-top:100px">
  <div class="row d-flex justify-content-center">
    <div class="col-10">
    <div class="d-flex justify-content-around">
      <div>
          <h6>Home</h6>
          <h6>Help</h6>
          <h6>Work with us</h6>
      </div>
      <div>
          <h6>About</h6>
          <h6>Terms</h6>
          <h6>Guideline</h6>
      </div>
    </div>
    <hr>
      <div class="d-flex justify-content-center mt-4">
        <div style="width: 100px;"class="d-flex justify-content-around">
          <i class="fa-brands fa-twitter"></i>
          <i class="fa-brands fa-facebook"></i>
          <i class="fa-brands fa-instagram"></i>
        </div>

      </div>
      <div class="d-flex justify-content-center mt-4">
        <h5>Triptip.com</h5>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/shared/_landing_home.html.erb
<div id="landing-background" style="height: 500px;">
</div>

app/views/shared/_list_of_card.html.erb
<%# index %>
<div class="mt-4 col-lg-3 d-flex row flex-row flex-nowrap overflow-auto" style="margin: 0 auto; width: 100%">
<% @posts.each do |post| %>
  <div class="card me-5" style="width: 400px;">
     <% if post.photo.attached? %>
        <%= cl_image_tag post.photo.key, width: 400, crop: :fill %>
      <% else %>
        <img style="width:380px;" src="https://elcomercio.pe/resizer/VBT_5K1XgES0ec_-SjauADEHd_I=/1200x800/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/YZE2DDHNKNDXJNSFLFTAKPUUGU.jpg" alt="">
      <% end %>
      <div class="d-flex">
        <img class="circle" src="https://www.freeiconspng.com/thumbs/account-icon/account-icon-33.png" style="height:30px; width:30px" alt="">
        <%= User.find(post.user_id).first_name %>
        <h5 class="card-title">Card title</h5>
      </div>
    <div class="card-body">
      <p class="card-text"><%= post.content %></p>
      <%= link_to "Show", post_path(post), class:"btn btn-light" %>
      <i class="fa-regular fa-comment"></i>

      <%# like button %>


      <% if post.user_id == current_user.id %>
        <%= button_to post_likes_path(post), method: :delete, class:"btn btn-outline-primary" do %>
          <p>unlike</p>
          <i class="fa-solid fa-heart"></i>
        <% end %>
      <% else %>
        <%= button_to post_likes_path(post), method: :post, class:"btn btn-primary" do %>
        <p>like</p>
          <i class="fa-regular fa-heart"></i>
        <% end %>
      <% end %>

      <%= simple_form_for([post, @comment]) do |f|%>
        <%= f.input :text %>
        <%= f.button :submit, "Comment"%>
      <% end %>
    </div>
  </div>
<% end %>
</div>

app/views/shared/_logged_in_home.html.erb
<div style="">
 <div class="d-flex justify-content-center" style="margin-top: 40px;">
  <div>
    <%# div white 1 %>
    <div class="" style="box-shadow: 0 0 15px rgba(0,0,0,0.2); height:400px; width: 400px; background-color: white;">

      <div class="d-flex justify-content-center">
        <% if current_user.avatar.attached? %>
          <%= cl_image_tag current_user.avatar.key, height: 150, width: 150, crop: :fill, class:"circle" %>
        <% else %>
          <img src="https://www.freeiconspng.com/thumbs/account-icon/account-icon-33.png" class="circle" style="height:150px; width:150px" alt="">
        <% end %>

        <div style="margin-top:30px">
          <h4><%= "Hello #{current_user.first_name}" %></h4>
          <%= link_to "Edit account", edit_user_registration_path(current_user), class:"btn btn-light"  %>
          <% if current_user.about.present? %>
            <%= link_to "Profile Setting", edit_user_about_path(current_user, current_user.about.id), class:"mt-2 btn btn-light" %>
          <% else %>
            <%= link_to "Profile Setting", new_user_about_path(current_user), class:"mt-2 btn btn-light" %>
          <% end %>
        </div>
      </div>

      <% if current_user.about.present? %>
        <% if current_user.about.number_of_countries.present?%>
          <div style="margin-left:70px" class="d-flex mt-3">
            <p class="me-3">Visitied Countries</p>
            <%= current_user.about.number_of_countries %>
          </div>
        <% end %>
        <% if current_user.about.number_of_met_people.present? %>
          <div style="margin-left:70px" class="d-flex mt-3">
            <p class="me-3">You met from this app</p>
            <%= current_user.about.number_of_met_people %>
          </div>
        <% end %>
        <% if current_user.about.number_of_friends.present? %>
          <div style="margin-left:70px" class="d-flex mt-3">
            <p class="me-3">Friends from differnt countries</h3>
            <%= current_user.about.number_of_friends %>
          </div>
        <% end %>
      <% end %>
    </div>


     <%# div white 2 %>
    <div class=" mt-4" style="box-shadow: 0 0 15px rgba(0,0,0,0.2); height: 400px; width: 400px; background-color: white;">
      <h4>Todo list</h4>
    </div>
  </div>

  <div class="">
    <div class="d-flex">
      <%# div white 3 %>
      <div class="ms-4 me-2 d-flex justify-content-center" style="box-shadow: 0 0 15px rgba(0,0,0,0.2); height: 100px; width: 330px; background-color: #005051;">
        <div>
          <h3 style="color:white">Post my Triptip</h3>
          <%= link_to "Post", new_post_path, class:"btn btn-light", style:"width: 80%; margin: 0 auto" %>
        </div>
      </div>

      <%# div white 4 %>
      <div class="" style="box-shadow: 0 0 15px rgba(0,0,0,0.2); height: 100px; width: 360px; background-color: white; left:">
        <%= render "shared/current_address_input" %>
      </div>
    </div>

    <%# div green 5 %>
    <div class="mt-4 ms-4 me-4 " style="box-shadow: 0 0 15px rgba(0,0,0,0.2); height: 700px; width: 700px; background-color: #005051;">
      <h3 style="color:white" >Active Traveler</h3>

    </div>
  </div>
 </div>



<%= render "shared/card_home" %>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <h2 class="d-flex" style="color:#005051; font-weight:bold; font-color">
        <p>Tr</p>
        <p style="color:rgba(215,223,35,1);">i</p>
        <p>pt</p>
        <p style="color:rgba(215,223,35,1);">i</p>
        <p>p</p>
        <p>🎄</p>
      </h2>
    <% end %>

    <%= form_with url: posts_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
                          params[:query],
                          class: "form-control",
                          placeholder: "Search your information",
                          style:"width: 400px"%>

      <%= submit_tag "Search", class: "btn btn-light" %>
    <% end %>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Chats", chatrooms_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "index", posts_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>